export type RecommendationType = "Strong Buy" | "Buy" | "Hold" | "Avoid";

export interface ScreenerStock {
  symbol: string;
  name: string;
  sector: string;
  marketCap: "Large Cap" | "Mid Cap" | "Small Cap";
  price: number;
  revenueGrowth: number; // percentage
  roe: number; // percentage
  pe: number;
  debtEquity: number;
  aiScore: number;
  recommendation: RecommendationType;
}

export const screenerStocks: ScreenerStock[] = [
  {
    symbol: "TCS",
    name: "Tata Consultancy Services",
    sector: "IT Services",
    marketCap: "Large Cap",
    price: 3725,
    revenueGrowth: 18,
    roe: 27,
    pe: 28,
    debtEquity: 0.05,
    aiScore: 94,
    recommendation: "Strong Buy",
  },
  {
    symbol: "INFY",
    name: "Infosys Ltd",
    sector: "IT Services",
    marketCap: "Large Cap",
    price: 1680,
    revenueGrowth: 15,
    roe: 29,
    pe: 24,
    debtEquity: 0.08,
    aiScore: 88,
    recommendation: "Buy",
  },
  {
    symbol: "HDFCBANK",
    name: "HDFC Bank Ltd",
    sector: "Banking & Financials",
    marketCap: "Large Cap",
    price: 1690,
    revenueGrowth: 20,
    roe: 18,
    pe: 19,
    debtEquity: 0.12,
    aiScore: 91,
    recommendation: "Strong Buy",
  },
  {
    symbol: "RELIANCE",
    name: "Reliance Industries",
    sector: "Conglomerate",
    marketCap: "Large Cap",
    price: 2510,
    revenueGrowth: 14,
    roe: 12,
    pe: 26,
    debtEquity: 0.38,
    aiScore: 84,
    recommendation: "Buy",
  },
  {
    symbol: "ICICIBANK",
    name: "ICICI Bank Ltd",
    sector: "Banking & Financials",
    marketCap: "Large Cap",
    price: 1055,
    revenueGrowth: 16,
    roe: 17,
    pe: 18,
    debtEquity: 0.15,
    aiScore: 89,
    recommendation: "Buy",
  },
  {
    symbol: "WIPRO",
    name: "Wipro Ltd",
    sector: "IT Services",
    marketCap: "Large Cap",
    price: 398,
    revenueGrowth: 4,
    roe: 14,
    pe: 21,
    debtEquity: 0.18,
    aiScore: 52,
    recommendation: "Avoid",
  },
  {
    symbol: "SBIN",
    name: "State Bank of India",
    sector: "Banking & Financials",
    marketCap: "Large Cap",
    price: 625,
    revenueGrowth: 12,
    roe: 16,
    pe: 10,
    debtEquity: 1.45,
    aiScore: 86,
    recommendation: "Buy",
  },
  {
    symbol: "BAJFINANCE",
    name: "Bajaj Finance Ltd",
    sector: "Banking & Financials",
    marketCap: "Large Cap",
    price: 7240,
    revenueGrowth: 25,
    roe: 22,
    pe: 36,
    debtEquity: 0.95,
    aiScore: 78,
    recommendation: "Buy",
  },
  {
    symbol: "TATAMOTORS",
    name: "Tata Motors Ltd",
    sector: "Automotive",
    marketCap: "Large Cap",
    price: 645,
    revenueGrowth: 32,
    roe: 24,
    pe: 16,
    debtEquity: 0.85,
    aiScore: 92,
    recommendation: "Strong Buy",
  },
  {
    symbol: "MARUTI",
    name: "Maruti Suzuki India",
    sector: "Automotive",
    marketCap: "Large Cap",
    price: 11850,
    revenueGrowth: 9,
    roe: 15,
    pe: 29,
    debtEquity: 0.02,
    aiScore: 68,
    recommendation: "Hold",
  },
  {
    symbol: "KPITTECH",
    name: "KPIT Technologies",
    sector: "IT Services",
    marketCap: "Mid Cap",
    price: 1450,
    revenueGrowth: 38,
    roe: 26,
    pe: 65,
    debtEquity: 0.22,
    aiScore: 81,
    recommendation: "Buy",
  },
  {
    symbol: "DIXON",
    name: "Dixon Technologies",
    sector: "Electronics",
    marketCap: "Mid Cap",
    price: 6850,
    revenueGrowth: 45,
    roe: 23,
    pe: 85,
    debtEquity: 0.45,
    aiScore: 79,
    recommendation: "Buy",
  },
  {
    symbol: "CDSL",
    name: "Central Depository Services",
    sector: "Financial Services",
    marketCap: "Mid Cap",
    price: 1980,
    revenueGrowth: 28,
    roe: 31,
    pe: 48,
    debtEquity: 0.0,
    aiScore: 93,
    recommendation: "Strong Buy",
  },
  {
    symbol: "IRCTC",
    name: "Indian Railway Catering",
    sector: "Consumer Services",
    marketCap: "Mid Cap",
    price: 940,
    revenueGrowth: 19,
    roe: 42,
    pe: 55,
    debtEquity: 0.05,
    aiScore: 71,
    recommendation: "Hold",
  },
  {
    symbol: "ZOMATO",
    name: "Zomato Ltd",
    sector: "Consumer Services",
    marketCap: "Mid Cap",
    price: 185,
    revenueGrowth: 52,
    roe: 5,
    pe: 120,
    debtEquity: 0.01,
    aiScore: 73,
    recommendation: "Hold",
  },
  {
    symbol: "IDEA",
    name: "Vodafone Idea Ltd",
    sector: "Telecom",
    marketCap: "Mid Cap",
    price: 12,
    revenueGrowth: -2,
    roe: -85,
    pe: -5,
    debtEquity: 8.5,
    aiScore: 35,
    recommendation: "Avoid",
  },
  {
    symbol: "SUZLON",
    name: "Suzlon Energy Ltd",
    sector: "Energy",
    marketCap: "Small Cap",
    price: 42,
    revenueGrowth: 15,
    roe: 18,
    pe: 140,
    debtEquity: 0.6,
    aiScore: 61,
    recommendation: "Hold",
  },
  {
    symbol: "TATACOMM",
    name: "Tata Communications",
    sector: "Telecom",
    marketCap: "Mid Cap",
    price: 1720,
    revenueGrowth: 12,
    roe: 20,
    pe: 28,
    debtEquity: 1.1,
    aiScore: 76,
    recommendation: "Buy",
  },
];

export function getRecommendationForScore(score: number): RecommendationType {
  if (score >= 90) return "Strong Buy";
  if (score >= 75) return "Buy";
  if (score >= 60) return "Hold";
  return "Avoid";
}
